### ISSUE TITLE
Api e DataBase in PHP 

### ISSUE THREAD

**Issue by zhLisha** [Frowingg/git-branch-merge#1]
Scusate, potevo scrivervi in privato, ma volevo provare le ISSUES hahaha

Comunque, 
Io e @DNParadox  abbiamo finito la prima stesura dell'api e database, abbiamo fatto un test lato back end e risultava tutto nella norma.

Nel caso @Gius993 o @RavgaCode  aveste dei problemi a richiamarla, noi siamo a disposizione :)

**Comment by Gius993** [comment]
si si nessun problema, tanto saremo tutti su zoom. Io nel frattempo ho creato giusto lo scheletro front anche  per capire bene come dividere le cose :D

**Comment by RavgaCode** [comment]
@zhLisha Scusa, mi ci sono messo ora. Non dovrebbero esserci problemi col database e api, ma in caso ti faccio sapere!
